# Generated by Django 5.2.5 on 2025-09-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='User',
            new_name='user',
        ),
    ]
